Add: create_repo.yaml

diff --git a/.github/workflows/part1/needs.yaml b/.github/workflows/part1/needs.yaml
--- a/.github/workflows/part1/needs.yaml
+++ b/.github/workflows/part1/needs.yaml
@@ -5,27 +5,26 @@ jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
-      - name: echo
-        run: echo "job1 done"
-
+    - name: echo
+      run: echo "job1 done"
   job2:
     runs-on: ubuntu-latest
     needs: [job1]
     steps:
-      - name: echo
-        run: echo "job2 done"
+    - name: echo
+      run: echo "job2 done"
 
   job3:
     runs-on: ubuntu-latest
     steps:
-      - name: echo
-        run: |
-          echo "job3 failed"
-          exit 1
-
+    - name: echo
+      run: |
+        echo "job3 failed"
+        exit 1
+      
   job4:
     runs-on: ubuntu-latest
     needs: [job3]
     steps:
-      - name: echo
-        run: echo "job4 done"
+    - name: echo
+      run: echo "job4 done"
